In [1]:
import numpy as np

np.random.randint(101)


79

In [2]:
np.random.rand(10)

array([0.67014377, 0.27327855, 0.32091535, 0.54102403, 0.94425635,
       0.75851086, 0.37143657, 0.30852928, 0.88448108, 0.21927478])

In [4]:
np.random.randn(5) #its range is -1 to 1

array([ 0.48091134, -0.33838429,  0.85193221,  0.14064885, -1.15047738])

In [9]:
np.ones(2)

array([1., 1.])

In [23]:
arr = np.arange(0,16)
arr
arr.reshape(4,4)
arr[1:,2]

IndexError: too many indices for array

In [31]:
ar = np.arange(1,17).reshape(4,4)
ar.max()
ar.min()
print(ar)
ar[0:1,::2]#use this argument for column value to jump values by 2

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


array([[1, 3]])

In [40]:
ar = np.arange(1,17).reshape(4,4)
ar>5
ar[ar>9]
ar[ar%2==0 & ar>10]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()